TST: Added UnitTests for Matchers.java & ByteArrayMatchers.java
Testibus-Team4/yoko pull request #15
Opened 2022-10-06 12:54 UTC by SimonaStavarache

2022-10-06 14:35 UTC, austin0 approved these changes, later dismissed

2022-10-11 10:09 UTC, joe-chacko requested changes
See comments for details

2022-10-11 10:09 UTC, joe-chacko commented on yoko-testify/src/test/java/testify/matchers/ByteArrayMatchersTest.java
> +        assertTrue(baseMatcherObject.matches(new byte[]{12, 13, 100, 127, 0xc}));
Use `new byte[]{0x0c, 0x0d, 0x64, 0x7f, 0x0c}`

2022-10-11 10:09 UTC, joe-chacko commented on yoko-testify/src/test/java/testify/matchers/ByteArrayMatchersTest.java
> +        assertFalse(baseMatcherObject.matches(new byte[]{12, 13, 100}));
use hex int literals

2022-10-11 10:09 UTC, joe-chacko commented on yoko-testify/src/test/java/testify/matchers/ByteArrayMatchersTest.java
> +        baseMatcherObject.describeMismatch(new byte[]{12, 13, 100}, testDescription);
use hex int literals

2022-10-11 13:16 UTC, SimonaStavarache commented on yoko-testify/src/test/java/testify/matchers/ByteArrayMatchersTest.java
> +        assertTrue(baseMatcherObject.matches(new byte[]{12, 13, 100, 127, 0xc}));
Solved

2022-10-11 13:17 UTC, SimonaStavarache commented on yoko-testify/src/test/java/testify/matchers/ByteArrayMatchersTest.java
> +        assertFalse(baseMatcherObject.matches(new byte[]{12, 13, 100}));
Solved

2022-10-11 13:17 UTC, SimonaStavarache commented on yoko-testify/src/test/java/testify/matchers/ByteArrayMatchersTest.java
> +        baseMatcherObject.describeMismatch(new byte[]{12, 13, 100}, testDescription);
Solved

2022-10-12 09:04 UTC, austin0 approved these changes

2022-10-12 09:30 UTC, SimonaStavarache commented
Closed #179

2022-10-12 09:30 UTC, merged